//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andover.Domain.Components.Database.Provider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andover.Domain.Components.Database.Provider.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT count([Id]) as RowCountValue FROM [Master].[dbo].[EventQueue].
        /// </summary>
        internal static string CountEventQueue {
            get {
                return ResourceManager.GetString("CountEventQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT([Id]) as RowCountValue FROM [Master].[dbo].[History].
        /// </summary>
        internal static string CountHistory {
            get {
                return ResourceManager.GetString("CountHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT count([Id]) as RowCountValue FROM [Master].[dbo].[PublishQueue].
        /// </summary>
        internal static string CountPublishQueue {
            get {
                return ResourceManager.GetString("CountPublishQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	[name] as DatabaseName,
        ///	compatibility_level,	
        ///	CONVERT(varchar(10),DATABASEPROPERTYEX([Name] , &apos;IsAutoShrink&apos;)) AS AutoShrink,		
        ///	CONVERT(varchar(10),DATABASEPROPERTYEX([Name] , &apos;IsAutoClose&apos;)) AS AutoClose,		
        ///	recovery_model_desc AS [Recovery Model]		 FROM sys.databases 
        ///ORDER BY DatabaseName.
        /// </summary>
        internal static string DatabaseProperties {
            get {
                return ResourceManager.GetString("DatabaseProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ps.database_id, ps.OBJECT_ID,
        ///ps.index_id, b.name,
        ///ps.avg_fragmentation_in_percent
        ///FROM sys.dm_db_index_physical_stats (DB_ID(), NULL, NULL, NULL, NULL) AS ps
        ///INNER JOIN sys.indexes AS b ON ps.OBJECT_ID = b.OBJECT_ID
        ///AND ps.index_id = b.index_id
        ///WHERE ps.database_id = DB_ID()
        ///ORDER BY ps.avg_fragmentation_in_percent desc.
        /// </summary>
        internal static string IndexFragmentation {
            get {
                return ResourceManager.GetString("IndexFragmentation", resourceCulture);
            }
        }
    }
}
